version: '3.4'

services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  catalog.api:
    build:
      context: ./Services/Catalog/Catalog.API
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - catalogdb

volumes:
  postgres_catalog:
